const GITHUB_API_VERSION = '2022-11-28';

/**
 * @typedef {{
 *   text: string,
 *   userId: string,
 *   threadTs: string,
 *   requestedBy?: string,
 *   snapshot?: import('./context-snapshot.js').ContextSnapshot,
 * }} GitHubIssueInput
 */

/**
 * @typedef {{
 *   number: number,
 *   url: string,
 * }} GitHubIssueResult
 */

/**
 * @typedef {{
 *   number: number,
 *   state: string,
 *   url: string,
 * }} GitHubIssueStatus
 */

/**
 * @typedef {{
 *   token: string,
 *   owner: string,
 *   repo: string,
 * }} GitHubConfig
 */

/**
 * @typedef {{
 *   debug?: (message: string) => void,
 *   error?: (message: string) => void,
 * }} GitHubLogger
 */

export class GitHubServiceError extends Error {
  /**
   * @param {string} message
   * @param {{ status?: number, cause?: unknown }} [options]
   */
  constructor(message, options = {}) {
    super(message);
    this.name = 'GitHubServiceError';
    this.status = options.status;
    this.cause = options.cause;
  }
}

/**
 * @returns {GitHubConfig}
 */
export function getGitHubConfig() {
  const token = process.env.GITHUB_TOKEN?.trim();
  const owner = process.env.GITHUB_OWNER?.trim();
  const repo = process.env.GITHUB_REPO?.trim();

  if (!token || !owner || !repo) {
    throw new GitHubServiceError('GitHub configuration is incomplete.');
  }

  return { token, owner, repo };
}

/**
 * @param {string} text
 * @returns {string}
 */
export function formatIssueTitle(text) {
  const title = text
    .replace(/^\s*["']?/, '')
    .replace(/\b(?:i'll|i will|we'll|we will|let's|let me|i can)\s+/i, '')
    .replace(/[.!?]+$/g, '')
    .trim();

  if (!title) {
    return 'Anchor commitment';
  }

  return title.charAt(0).toUpperCase() + title.slice(1);
}

/**
 * @param {GitHubIssueInput} input
 * @returns {string}
 */
export function formatIssueBody({ text, userId, threadTs, requestedBy, snapshot }) {
  if (snapshot) {
    return [
      '# Context Snapshot',
      '',
      '## Summary',
      snapshot.summary || text,
      '',
      '## Requirements',
      formatMarkdownList(snapshot.requirements),
      '',
      '## Dependencies',
      formatMarkdownList(snapshot.dependencies),
      '',
      '## Potential Risks',
      formatMarkdownList(snapshot.potentialRisks, { emptyText: 'No obvious risks detected.' }),
      '',
      '## Due Date',
      snapshot.dueDate || 'Not specified',
      '',
      '## AI Analysis',
      `Confidence: ${formatMetadataValue(snapshot.confidence)}`,
      `Complexity: ${formatMetadataValue(snapshot.estimatedComplexity)}`,
      '',
      'Labels:',
      formatMarkdownList(snapshot.labels),
      '',
      '## Original Commitment',
      formatQuotedText(text),
      '',
      '## Requested By',
      formatRequestedBy(requestedBy, userId),
      '',
      'Generated by Anchor',
    ]
      .filter((line) => line !== '')
      .join('\n');
  }

  return [
    'Created by Anchor',
    '',
    'Original commitment:',
    text,
    '',
    'Slack User:',
    userId,
    '',
    'Slack Thread:',
    threadTs,
    '',
    'Status:',
    'Open',
  ].join('\n');
}

/**
 * @param {string[]} items
 * @param {{ emptyText?: string }} [options]
 * @returns {string}
 */
function formatMarkdownList(items, options = {}) {
  if (!Array.isArray(items) || items.length === 0) {
    return options.emptyText ?? 'Not specified';
  }

  return items.map((item) => `- ${item}`).join('\n');
}

/**
 * @param {string} value
 * @returns {string}
 */
function formatMetadataValue(value) {
  if (!value) {
    return 'Not specified';
  }

  return value
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * @param {string} text
 * @returns {string}
 */
function formatQuotedText(text) {
  const normalizedText = text.trim();
  if (!normalizedText) {
    return '> Not specified';
  }

  return normalizedText
    .split(/\r?\n/)
    .map((line) => `> ${line}`)
    .join('\n');
}

/**
 * @param {string | undefined} requestedBy
 * @param {string} userId
 * @returns {string}
 */
function formatRequestedBy(requestedBy, userId) {
  const formatted = requestedBy?.trim();
  if (formatted) {
    return formatted.startsWith('@') ? formatted : `@${formatted}`;
  }

  return userId ? 'Slack user' : 'Not specified';
}

/**
 * Create a GitHub issue for a confirmed commitment.
 * @param {GitHubIssueInput} input
 * @param {{ fetchImpl?: typeof fetch, config?: GitHubConfig, logger?: GitHubLogger }} [options]
 * @returns {Promise<GitHubIssueResult>}
 */
export async function createIssue(input, options = {}) {
  const config = options.config ?? getGitHubConfig();
  const fetchImpl = options.fetchImpl ?? fetch;
  const logger = options.logger;
  const url = `https://api.github.com/repos/${config.owner}/${config.repo}/issues`;

  logger?.debug?.(`Creating GitHub issue: owner=${config.owner}, repo=${config.repo}, url=${url}`);

  const response = await fetchImpl(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': GITHUB_API_VERSION,
    },
    body: JSON.stringify({
      title: input.snapshot?.title || formatIssueTitle(input.text),
      body: formatIssueBody(input),
    }),
  }).catch((error) => {
    logger?.error?.(
      `GitHub issue creation request failed: owner=${config.owner}, repo=${config.repo}, url=${url}, error=${error}`,
    );
    throw new GitHubServiceError('GitHub issue creation request failed.', { cause: error });
  });

  if (!response.ok) {
    const responseBody = await readResponseBody(response);
    logger?.error?.(
      `GitHub issue creation failed: owner=${config.owner}, repo=${config.repo}, url=${url}, status=${response.status}, response_body=${responseBody}`,
    );
    throw new GitHubServiceError('GitHub issue creation failed.', { status: response.status });
  }

  const data = await response.json();
  if (typeof data.number !== 'number' || typeof data.html_url !== 'string') {
    logger?.error?.(
      `GitHub issue creation returned an invalid response: owner=${config.owner}, repo=${config.repo}, url=${url}`,
    );
    throw new GitHubServiceError('GitHub issue creation returned an invalid response.');
  }

  return {
    number: data.number,
    url: data.html_url,
  };
}

/**
 * Get a GitHub issue by number.
 * @param {number} issueNumber
 * @param {{ fetchImpl?: typeof fetch, config?: GitHubConfig, logger?: GitHubLogger }} [options]
 * @returns {Promise<GitHubIssueStatus>}
 */
export async function getIssue(issueNumber, options = {}) {
  const config = options.config ?? getGitHubConfig();
  const fetchImpl = options.fetchImpl ?? fetch;
  const logger = options.logger;
  const url = `https://api.github.com/repos/${config.owner}/${config.repo}/issues/${issueNumber}`;

  logger?.debug?.(`Fetching GitHub issue: owner=${config.owner}, repo=${config.repo}, url=${url}`);

  const response = await fetchImpl(url, {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': GITHUB_API_VERSION,
    },
  }).catch((error) => {
    logger?.error?.(
      `GitHub issue fetch request failed: owner=${config.owner}, repo=${config.repo}, url=${url}, error=${error}`,
    );
    throw new GitHubServiceError('GitHub issue fetch request failed.', { cause: error });
  });

  if (!response.ok) {
    const responseBody = await readResponseBody(response);
    logger?.error?.(
      `GitHub issue fetch failed: owner=${config.owner}, repo=${config.repo}, url=${url}, status=${response.status}, response_body=${responseBody}`,
    );
    throw new GitHubServiceError('GitHub issue fetch failed.', { status: response.status });
  }

  const data = await response.json();
  if (typeof data.number !== 'number' || typeof data.state !== 'string' || typeof data.html_url !== 'string') {
    logger?.error?.(
      `GitHub issue fetch returned an invalid response: owner=${config.owner}, repo=${config.repo}, url=${url}`,
    );
    throw new GitHubServiceError('GitHub issue fetch returned an invalid response.');
  }

  return {
    number: data.number,
    state: data.state,
    url: data.html_url,
  };
}

/**
 * @param {Response} response
 * @returns {Promise<string>}
 */
async function readResponseBody(response) {
  if (typeof response.text !== 'function') {
    return '<unavailable>';
  }

  return response.text().catch((error) => `Unable to read GitHub response body: ${error}`);
}
